cmake --workflow --preset="clang-17-release"
cmake --workflow --preset="clang-17-libc++release"
cmake --workflow --preset="clang-16-release"
cmake --workflow --preset="clang-16-libc++release"
cmake --workflow --preset="clang-15-release"
cmake --workflow --preset="clang-15-libc++release"
cmake --workflow --preset="gcc-13-release"
cmake --workflow --preset="gcc-12-release"
